# Generated by Django 3.0.2 on 2020-01-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInfo',
            fields=[
                ('application_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_csv', models.FileField(upload_to='item_csv', verbose_name='item csv')),
                ('stock_csv', models.FileField(upload_to='stock_csv', verbose_name='stock csv')),
                ('item_count', models.IntegerField(verbose_name='登録商品数')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileErrorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(max_length=100, verbose_name='エラータイミング')),
                ('line_number', models.IntegerField(verbose_name='行番号')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='エラー')),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowma.UploadedFile', verbose_name='親ファイル')),
            ],
        ),
    ]
